#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

blacklist = ["~/.mozilla", "~/.gemini", "~/Downloads"]

[default_session]
# startup_command = "nvim -c ':lua Snacks.picker.files()'"
preview_command = "eza --tree --follow-symlinks --level=2 --all --git --icons --color=always {}"

[[wildcard]]
pattern = "~/projects/**"
startup_command = "eza --tree --follow-symlinks --level=2 --all --git --icons --color=always"

[[session]]
name = "config|tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "config|nvim"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "config|sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
