# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       2
outer.bottom =     2
outer.top =        2
outer.right =      2

[mode.main.binding]
# cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

cmd-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

cmd-left = 'focus left'
cmd-down = 'focus down'
cmd-up = 'focus up'
cmd-right = 'focus right'

cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
ctrl-cmd-s = 'split horizontal'
ctrl-cmd-v = 'split vertical'

cmd-f = 'fullscreen'

ctrl-cmd-w = 'layout v_accordion' # 'layout stacking' in i3
ctrl-cmd-t = 'layout h_accordion' # 'layout tabbed' in i3
ctrl-cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
# cmd-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# cmd-a = 'focus parent'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

cmd-shift-c = 'reload-config'

cmd-shift-r = 'mode resize'

[mode.resize.binding]
h =     'resize width  -25'
j =     'resize height +25'
k =     'resize height -25'
l =     'resize width  +25'
left =  'resize width  -25'
down =  'resize height +25'
up =    'resize height -25'
right = 'resize width  +25'
enter = 'mode main'
esc =   'mode main'
