# Template for an IMAP account via mbsync
[personal]
source            = maildir://~/.local/share/mail/personal
outgoing          = env MSMTP=/home/uchoa/.local/bin/msmtp-wrapper.py msmtpq --read-envelope-from --read-recipients
default           = INBOX
from              = André Uchôa <uchoa@pobox.com>
copy-to           = Sent
postpone          = Drafts

# Template for a Gmail account via lieer + notmuch
[scienti]
source            = notmuch://~/.local/share/mail
outgoing          = env MSMTP=/home/uchoa/.local/bin/msmtp-wrapper.py msmtpq --read-envelope-from --read-recipients
default           = INBOX
from              = André Uchôa <uchoa@scienti.com.br>
copy-to           = Sent
postpone          = Drafts
# Virtual folders via notmuch queries
query-map         = ~/.config/aerc/scienti-queries.map
maildir-store     = ~/.local/share/mail
maildir-account-path = scienti
# Template for an IMAP account via mbsync
# Template for a Gmail account via lieer + notmuch
[begen]
source            = notmuch:///home/uchoa/.local/share/mail
outgoing          = env MSMTP=/home/uchoa/.local/bin/msmtp-wrapper.py msmtpq --read-envelope-from --read-recipients
default           = INBOX
from              = André Uchôa <uchoa@begen.ai>
copy-to           = Sent
postpone          = Drafts
# Virtual folders via notmuch queries
query-map         = ~/.config/aerc/begen-queries.map
maildir-store     = ~/.local/share/mail
maildir-account-path = begen
[outbox]
source            = maildir://~/.msmtp.queue
default           = .
from              = Queue <queue@localhost>
